  CREATE USER BLOOD_DONATION_DATABASE
  IDENTIFIED BY 12345678
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON users;

grant create database link to BLOOD_DONATION_DATABASE;
grant create procedure to BLOOD_DONATION_DATABASE;
grant create sequence to  BLOOD_DONATION_DATABASE;
grant create session to BLOOD_DONATION_DATABASE;
grant create synonym to  BLOOD_DONATION_DATABASE;
grant create table to  BLOOD_DONATION_DATABASE;
grant create trigger to  BLOOD_DONATION_DATABASE;
grant create type to BLOOD_DONATION_DATABASE;
grant create view to  BLOOD_DONATION_DATABASE;
GRANT SELECT ON dba_jobs_running TO  BLOOD_DONATION_DATABASE;
GRANT CREATE job TO  BLOOD_DONATION_DATABASE;
GRANT CREATE EXTERNAL job TO BLOOD_DONATION_DATABASE;
